name: mujoco
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - libcxx=20.1.8
  - libexpat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - python=3.12.12
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - etils==1.13.0
      - fsspec==2025.12.0
      - glfw==2.10.0
      - importlib-resources==6.5.2
      - mujoco==3.4.0
      - numpy==2.3.5
      - pynput==1.8.1
      - pyobjc-core==12.1
      - pyobjc-framework-applicationservices==12.1
      - pyobjc-framework-cocoa==12.1
      - pyobjc-framework-coretext==12.1
      - pyobjc-framework-quartz==12.1
      - pyopengl==3.1.10
      - six==1.17.0
      - typing-extensions==4.15.0
      - zipp==3.23.0
prefix: /opt/anaconda3/envs/mujoco
